service: dojobot

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    DATABASE_ENVIRONMENT: ${opt:stage, 'dev'}

functions:
  app:
    handler: src/server.DojoBotLambda
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
